### ISSUE TITLE
replace `(q.head + n) & modBits` with next() in Rotate

### ISSUE THREAD

**Issue by 63isOK** [gammazero/deque#11]
q.head = (q.head - 1) & modBits
=>
q.head = q.prev(q.head)

q.head = (q.head + n) & modBits
=>
q.head = q.next(q.head + n - 1)

**Comment by gammazero** [comment]
Thank you for the suggestion.  The reason that `Rotate` does not call `prev` or `next` is to avoid recalculating `modBits` that would happen if calling those functions.
